import InputArea from '@/components/InputArea';
import { FormEvent, useState } from 'react';
import Main from '@/components/Main';
import Head from 'next/head';

export default function Home() {
  const [historyRecord, setHistoryRecord] = useState<Array<JSX.Element>>([<Main />]);
  const [isClear, setIsClear] = useState<boolean>(false);

  const handleForm = (e: FormEvent) => {
    console.log(historyRecord);
    e.preventDefault();

    if (isClear) {
      setHistoryRecord([<Main />]);

      setIsClear(false);
    } else {
      setHistoryRecord([...historyRecord, <Main />]);
    }
  };

  const handleData = (fromChild: string) => {
    if (fromChild == 'clear') setIsClear(true);
  };

  return (
    <>
      <Head>
        <title>root@cantez</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div>
        {historyRecord.map((el, idx) => (
          <form onSubmit={handleForm} key={idx}>
            <Main onData={handleData} />
          </form>
        ))}
      </div>
    </>
  );
}
