import InputArea from '@/components/InputArea';
import { DisplayCommandT, HistoryElementT } from '@/types/root';
import { MainContext } from './_app';
import { useContext } from 'react';
import Head from 'next/head';

export default function Home() {
  const { history } = useContext(MainContext);

  const invalidCommands: Array<string> = [
    'cd',
    'mkdir',
    'touch',
    'cat',
    'node',
    'npm',
    'git',
    'env',
    'py',
    'python',
  ];

  const validCommands: Array<DisplayCommandT> = [
    {
      cmd: 'pwd',
      res: '/home/user/cantez',
    },
    {
      cmd: 'sudo rm -rf',
      res: 'Nice try fella',
    },
    {
      cmd: 'ps intro',
      res: 'Hi there I\'m Alperen, a blockchain developer. Welcome to my nerdy-looking porfolio! Use "ps ls" to see other commands to navigate in this website.',
    },
    {
      cmd: 'npm',
      res: 'npm: unresolved package',
    },
    {
      cmd: 'ls',
      res: `.next\nnode_modules\npublic\nsrc\nstyles\n.gitignore\n.prettierrc\nnext-env.d.ts\nnext.config.js\npackage-lock.json\npackage.json\nroot.d.ts\ntsconfig.json\nyarn.lock
      `,
    },
    {
      cmd: 'ps ls',
      res: 'ps about\nps social\nps forkme\nps ls (recursive)\n',
    },
    {
      cmd: 'ps social',
      res: 'linkedin: https://www.linkedin.com/in/alperencantez\ngithub: https://github.com/alperencantez\nemail: alperen.cantez@outlook.com\n',
    },
    {
      cmd: 'ps forkme',
      res: 'thank you for your interest in this project!\nthe repo: https://github.com/alperencantez/portfolio.sh',
    },
    {
      cmd: 'ps about',
      res: "I'm a self-taught software developer who is mainly passionate about JavaScript technologies.\nMy journey started back in 2020 wondering what really programming is and I've been learning and building ever since.\nI am currently working as a blockchain developer at Areon Network and improving my core-blockchain skills in my spare time.\n\nTech Stack\n-------------\nFront-end -> React/React Native, Next.js, TailwindCSS, SASS/SCSS, Vue.js\nBack-end -> Node.js (Express), SQL (MYSSQL - Postgres), Python (Flask - FastAPI), MongoDB\n\nFluent In\n-------------\nJavaScript/TypeScript, Python, Go\n\nTools\n-------------\nVersion Control (Git) - API Testing - Bash\n\n",
    },
  ];

  const invalidityChecker = (checkStr: string): number => {
    return invalidCommands.findIndex((item: string) => item == checkStr);
  };

  return (
    <>
      <Head>
        <title>root@cantez</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div>
        {history.map((item: HistoryElementT, idx: number) => {
          const promptAsArray = item.prompt.split(' ');
          let invalidMessage: string = '';

          for (let arg of promptAsArray) {
            const idx: number = invalidityChecker(arg);

            if (idx !== -1) {
              invalidMessage = 'Permission Denied';
              break;
            }
          }

          return (
            <div key={idx}>
              <div style={{ display: 'flex' }}>
                <label htmlFor='input'>
                  <code style={{ color: '#30d904', fontWeight: 500 }}>root@cantez</code>
                  :∼$
                </label>
                <input type='text' id='input' width='full' value={item.prompt} disabled spellCheck='false' />
              </div>

              <pre style={{ margin: 0, wordWrap: 'break-word' }}>
                {invalidMessage}
                {invalidityChecker(item.prompt) == -1 &&
                  validCommands.map((command) => item.prompt == command.cmd && command.res)}
              </pre>
            </div>
          );
        })}

        <InputArea />
      </div>
    </>
  );
}
